### ISSUE TITLE
Download links provide gh-pages branch.

### ISSUE THREAD

**Issue by joel0** [kdeloach/workman#3]
The download links go to https://github.com/kdeloach/workman/zipball/gh-pages, which is gh-pages branch instead of the master branch at https://github.com/kdeloach/workman/zipball/master.  There are 3 links on http://workmanlayout.org/ that need to be updates (2 in the header: tar.gz, zip, and 1 near the bottom: zip).

**Comment by kdeloach** [comment]
Fixed by #4
