### ISSUE TITLE
Capslock + Ctrl does not work as Backspace + Ctrl

### ISSUE THREAD

**Issue by ghost** [kdeloach/workman#6]
The Capslock key is mapped to backspace in workman. However, it does not work as Backspace + Ctrl does rendering the capslock mapping an inferior version of backspace. Is this intended behaviour?

**Comment by kdeloach** [comment]
I don't understand your question. What OS are you using and how did you install Workman? What is the expected vs actual behavior?

**Comment by kdeloach** [comment]
Please create an issue at https://github.com/workman-layout/Workman if this is still relevant.
