### ISSUE TITLE
Workman with Polish characters?

### ISSUE THREAD

**Issue by BartlomiejSkwira** [kdeloach/workman#8]
Hey, does anyone know if it's possible to have Workman layout and polish accent characters like: `ąęćż` (In a QWERTY layout I would have to do `ALT + a` to get `ą`) 

Or would I have to create such a layout for myself? I'm on Mac Osx

**Comment by kdeloach** [comment]
You'll have to create a new keyboard layout. Looks like the keyboard layout editor used for the existing Mac layouts is [Ukelele](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ukelele). I'm also using Mac so could help test this.

https://github.com/kdeloach/workman/tree/master/mac

**Comment by BartlomiejSkwira** [comment]
Yeah I've started working with Ukelele yesterday to create a Polish version of Workman, took me a bit to figure out how it actually works. @kdeloach where should I place the layout file? I'm thinking of 2 solutions:
1. The simple one - name the Polish version something like `Contents/Resources/Workman_PL.keylayout` and just leave it in the Resouces dir
2. Create separate directories for English and Polish languages:
`Contents/Resources/en/`
`Contents/Resources/pl`
Move all current layout files to the `en` dir, create a new Polish layout and place it in `pl` dir.

Which solution should I take?

**Comment by BartlomiejSkwira** [comment]
I created a Polish Workman layout, here is the file. I can create a pull request (so its available in your repo) but you need to answer the question above about dir structure. 
[Workman_PL.zip](https://github.com/kdeloach/workman/files/2314522/Workman_PL.zip)

**Comment by kdeloach** [comment]
I vote for the simple approach. I'm unavailable for a couple days but I'll try to test this on Monday.

**Comment by kdeloach** [comment]
Fixed by #10
