### ISSUE TITLE
use a shared github org?

### ISSUE THREAD

**Issue by ryenus** [kdeloach/workman#9]
To promote Workman Layout, what about using a shared GitHub organization?
this way it would have benefits like:
* a stronger branding, 
* easier to find, 
* also easier to collaborate.

I checked and found the [workman-layout][1] organization is available, so I just registered it and granted you the ownership as well as @ojbucao.

I really think we should work harder to challenge the defacto status quo of QWERTY.

[1]: https://github.com/workman-layout/

**Comment by kdeloach** [comment]
Great idea! 

We should transfer ownership of [ojbucao/Workman](https://github.com/ojbucao/Workman) to [workman-layout](https://github.com/workman-layout), if possible.

I can port over any missing changes from my fork. Once the repo is moved to the new location I'll update the DNS for https://workmanlayout.org/ to point there.

**Comment by ojbucao** [comment]
I transferred the repo. I appreciate both of your involvement in this.

**Comment by kdeloach** [comment]
I'm going to sync missing changes to the primary repository and delete this fork now.
